description: >
  Use the Orb to deploy staging when a PR is merged and to deploy production when the workflow is
  approved via CircleCI.

usage:
  version: 2.1

  orbs:
    opsworks: nebulab/opsworks-deployment@6.0.0

  workflows:
    build-and-deploy:
      jobs:
        - build
        - opsworks/deploy:
            name: deploy-staging
            app_id: your-staging-opsworks-app-id
            stack_id: your-staging-opsworks-stack-id
            github_repo: myorg/myrepo
            slack_hook_url: https://your.slack.hook.url
            current_env: staging
            next_env: production
            requires:
              - build
            filters:
              branches:
                only: master
        - approve-production:
            requires:
              - deploy-staging
            type: approval
        - opsworks/deploy:
            name: deploy-production
            app_id: your-staging-opsworks-app-id
            stack_id: your-staging-opsworks-stack-id
            github_repo: myorg/myrepo
            slack_hook_url: https://your.slack.hook.url
            current_env: production
            requires:
              - approve-production

  jobs:
    build:
      docker:
        - image: circleci/ruby
      steps:
        - run your tests here
